import axiosInstance from '@/api/axiosInstance';

export type TaskStatus =
  | 'open'
  | 'in_progress'
  | 'pending_approval'
  | 'completed'
  | 'overdue'
  | 'cancelled';

export type TaskPriority = 'low' | 'medium' | 'high' | 'critical';

export interface TaskEntityRef {
  _id: string;
  name: string;
  entityCode: string;
}

export interface TaskLocationRef {
  _id: string;
  name: string;
  locationCode: string;
}

export interface TaskUserRef {
  _id: string;
  firstName: string;
  lastName: string;
  email: string;
}

export interface TaskComplianceRecordRef {
  _id: string;
  recordNumber: string;
  status: string;
  dueDate?: string;
  expiryDate?: string;
  rule?: {
    _id: string;
    name: string;
    code: string;
  };
}

export interface TaskItem {
  _id: string;
  title: string;
  description?: string;
  entity?: TaskEntityRef;
  location?: TaskLocationRef;
  complianceRecord?: TaskComplianceRecordRef;
  assignedTo?: TaskUserRef;
  priority: TaskPriority;
  dueDate?: string;
  status: TaskStatus;
  createdBy?: {
    _id: string;
    firstName: string;
    lastName: string;
  };
  completedBy?: {
    _id: string;
    firstName: string;
    lastName: string;
  };
  completedAt?: string;
  isAutoGenerated?: boolean;
  autoGenSource?: string;
  createdAt: string;
  updatedAt: string;
}

export interface TaskQueryParams {
  page?: number;
  limit?: number;
  search?: string;
  status?: TaskStatus | '';
  priority?: TaskPriority | '';
  entity?: string;
  location?: string;
  complianceRecord?: string;
  assignedTo?: string;
  overdueOnly?: boolean;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

export interface TaskMetrics {
  total: number;
  open: number;
  inProgress: number;
  pendingApproval: number;
  completed: number;
  overdue: number;
  cancelled: number;
}

export interface TaskListResponse {
  success: boolean;
  data: TaskItem[];
  pagination: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
    hasNextPage: boolean;
    hasPrevPage: boolean;
  };
}

export interface CreateTaskPayload {
  title: string;
  description?: string;
  entity?: string;
  location?: string;
  complianceRecord?: string;
  assignedTo?: string;
  priority: TaskPriority;
  dueDate?: string;
  status?: TaskStatus;
}

export const taskService = {
  async getTasks(params?: TaskQueryParams): Promise<TaskListResponse> {
    const res = await axiosInstance.get('/tasks', { params });
    return res.data;
  },

  async getMyTasks(params?: TaskQueryParams): Promise<TaskListResponse> {
    const res = await axiosInstance.get('/tasks/my-tasks', { params });
    return res.data;
  },

  async getOverdueTasks(params?: TaskQueryParams): Promise<TaskListResponse> {
    const res = await axiosInstance.get('/tasks/overdue', { params });
    return res.data;
  },

  async getMetrics(myOnly = false): Promise<TaskMetrics> {
    const res = await axiosInstance.get('/tasks/metrics', {
      params: myOnly ? { myOnly: 'true' } : {},
    });
    return res.data.data;
  },

  async getTaskById(id: string): Promise<TaskItem> {
    const res = await axiosInstance.get(`/tasks/${id}`);
    return res.data.data;
  },

  async createTask(data: CreateTaskPayload | Partial<TaskItem>): Promise<TaskItem> {
    const res = await axiosInstance.post('/tasks', data);
    return res.data.data;
  },

  async updateTask(id: string, data: Partial<CreateTaskPayload> | Partial<TaskItem>): Promise<TaskItem> {
    const res = await axiosInstance.put(`/tasks/${id}`, data);
    return res.data.data;
  },

  async updateTaskStatus(id: string, status: TaskStatus): Promise<TaskItem> {
    const res = await axiosInstance.patch(`/tasks/${id}/status`, { status });
    return res.data.data;
  },

  async deleteTask(id: string): Promise<void> {
    await axiosInstance.delete(`/tasks/${id}`);
  },

  async triggerAutomation(): Promise<{
    tasksCreated: number;
    notificationsSent: number;
    summary: Record<string, number>;
  }> {
    const res = await axiosInstance.post('/automation/run-checks');
    return res.data.data;
  },
};
